### ISSUE TITLE
Code listing for section "Seed the DB with Test Data" has error

### ISSUE THREAD

**Issue by michalgruda1** [aspnet/AspNetCore.Docs.pl-pl#15]
Code listing for section:
https://docs.microsoft.com/pl-pl/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio#seed-the-db-with-test-data
has an error. There is:
context.Courses.Add(c);

There should be:
context.Course.Add(c);

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Strony razor z programem EF Core w programie ASP.NET Core — Model danych — 5 8](https://docs.microsoft.com/pl-pl/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hello, @michalgruda1 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/13104

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
